### ISSUE TITLE
Cannot find .tempfile

### ISSUE THREAD

**Issue by Question2** [suloku/ChocoEdit#1] opened 2016-10-09 04:09 UTC
Uh dude, on the PC version it keeps complaining that it cannot find a ".tempfile"....what? Why does it need that file?

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\Users\Question\Documents\Square Enix\FINAL FANTASY VIII Steam.tempfile'.
File name: 'C:\Users\Question\Documents\Square Enix\FINAL FANTASY VIII Steam.tempfile'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at ChocoEdit.FileIO._read_data(Byte[]& buffer, String path)
   at ChocoEdit.FileIO.load_file(Byte[]& buffer, String& path, String filter)
   at ChocoEdit.MainForm.load_savegame(String filepath)
   at ChocoEdit.MainForm.Loadsave_butClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by suloku** [comment] 2016-10-18 12:12
Can you try running as admin?
The pc save is compressed and I used an external tool that is embedded in the program and extracted the first time it's run for convenience, but maybe that messes up things. The temp file is the decompressed file that is what should be edited (automatically loaded) then re-compressed when saving.

Works fine on my end :S

**Comment by Question2** [comment] 2016-10-23 10:43
Im already running as admin.

**Comment by Phoenix2312** [comment] 2017-07-26 21:31
Having the same issue... Running Windows 10 if that is any help.

**Comment by sgwildh** [comment] 2018-09-06 11:42
Correct, make sure you run the exe file as administrator and it will work.

**Comment by eyeonus** [comment] 2020-12-22 01:47
Running as admin does not work.

**Comment by nlangh** [comment] 2021-03-13 23:14
The problem seems to be the lzs.exe, I couldn't figure out what the real problem is, but decompressing the chocorpg.ff8 file with another tool like the https://github.com/myst6re/qt-lzs works. Note that you cannot simply replace the old lzs.exe with the new one, because ChocoEdit will replace it with the old one at startup.

How To:
- decompress savegame with other tool `lzs.exe -d path_to_your_savegame_file path_to_ChocoEdit_directory`
- rename decompressed file **chocorpg.ff8.dec** to **.tempfile**
- open ChocoEdit.exe and use it as usual

It's a monkey work, but it works.

**Comment by suloku** [comment] 2021-03-14 09:40
Sorry for the 5 years it took to solve this. It seems my logic to call lzs.exe didn't like folders with space (" ") characters on it. It should have worked fine if the program AND loaded file were in something like c:\chocoedit\ AND had no spaces in filenames. Most likely I did my testing with paths like that back in the day :(

In any case, should be working now, if someone can test I'll close the issue.

https://github.com/suloku/ChocoEdit/releases

**Comment by nlangh** [comment] 2021-03-14 11:05
Now I get this error, although the old version works fine on path c:\chocoedit. 

```
************** Exception Text **************
System.IO.FileNotFoundException: Could not find file 'C:\ChocoEdit_0.2b\.tempfile'.
File name: 'C:\ChocoEdit_0.2b\.tempfile'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at ChocoEdit.FileIO._read_data(Byte[]& buffer, String path)
   at ChocoEdit.FileIO.load_file(Byte[]& buffer, String& path, String filter)
   at ChocoEdit.MainForm.load_savegame(String filepath)
   at ChocoEdit.MainForm.Loadsave_butClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ChocoEdit
    Assembly Version: 1.0.7743.18830
    Win32 Version: 1.0.7743.18830
    CodeBase: file:///C:/ChocoEdit_0.2b/ChocoEdit.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by suloku** [comment] 2021-03-14 11:43
This is really strange, I redownloaded the file in the releases page, put it into and can't reproduce the error
Seems either lzs.exe isn't extracting/working or maybe antivirus is deleting it. Other possibility is lsz.exe not having permisions to write to c:\. This could be rulled out by running as administrator (but I am running it as normal user).
Have you tested other locations? Desktop for example.

**Comment by nlangh** [comment] 2021-03-14 12:13
I run lzs.exe as a normal user from the console and it works, but even when I try to run ChocoEdit.exe as administrator I get this error.

**Comment by suloku** [comment] 2021-03-14 12:17
I'll try testing on another laptop, because I'm not getting the error on mine. I'm currently under windows 10, are you running another windwos version?

**Comment by nlangh** [comment] 2021-03-14 12:18
Yes I am using windows 10. I get this console output and then it dies wifh the error above.

```cmd
Ficedula FFLZS v1.20 C:\CHOCOEDIT_0.2B\chocorpg.ff8 -> C:\CHOCOEDIT_0.2B\.TEMPFILE
Progress: [                                                  ]
```

**Comment by suloku** [comment] 2021-03-14 12:23
Seems everything is fine, but for some reason lzs.exe can't create the decompressed .tempfile...

Can you try this from command prompt?

"c:\Chocoedit_0.2B\lzs.exe" -d "c:\Chocoedit_0.2B\chocorpg.ff8" "c:\Chocoedit_0.2B\.tempfile"

**Comment by nlangh** [comment] 2021-03-14 12:29
yep thats not working, it get `Exception EReadError in module lzs.exe at 00019C77. Stream read error.`

but this works `lzs.exe chocorpg.ff8 .tempfile`, not helping but compression works.

**Comment by suloku** [comment] 2021-03-14 12:35
Sorry, I mistyped, maybe you noticed and corrected:
`"c:\Chocoedit_0.2B\lzs.exe" -d "c:\Chocoedit_0.2B\chocorpg.ff8" "c:\Chocoedit_0.2B\.tempfile"`


EDIT: github is editing the command.

**Comment by nlangh** [comment] 2021-03-14 12:37
I actually tested `lzs.exe -d chocorpg.ff8 .tempfile`, but I got the same error with paths

**Comment by suloku** [comment] 2021-03-14 18:37
I suspect the problem might have something to do with the naming of .tempfile, so I changed it to tempfile.ff8 in the program.
Still working fine on my end for everything I've tested.
Can you attach the chocorpg file you are using? Just to rule out the problem coming from it (which I don't think is the case).

I'm attaching a modified version of chocoedit that uses another naming convention, let's see if this works. Ideally I should port hyne's code for compresion/decompresion to c# and not use lzs.exe at all, but I don't think I would correctly port it.
[ChocoEdit.zip](https://github.com/suloku/ChocoEdit/files/6137323/ChocoEdit.zip)

**Comment by nlangh** [comment] 2021-03-14 18:57
Thanks, I will try it out.

I think you don't have to port it yourself, I used https://github.com/myst6re/qt-lzs as a workaround. Maybe you can integrate it. it is written in C++ and has the same license.

**Comment by nlangh** [comment] 2021-03-14 19:01
Unfortunately this didn't work either. But here is the savegame i am using.

[chocorpg.zip](https://github.com/suloku/ChocoEdit/files/6137366/chocorpg.zip)

**Comment by suloku** [comment] 2021-03-14 19:10
Well, still seems to work fine on my end.
I'll make an alternate version that uses qt-lzs and also add support to directly load and save decompressed chocorpg files so any external compresion/decompresion tool can be independently used.

**Comment by nlangh** [comment] 2021-03-14 19:12
thank you very much, that makes it easier for me.

**Comment by suloku** [comment] 2021-03-14 21:51
About using https://github.com/myst6re/qt-lzs, i found lots of implementations of lzs algorithm, but none directly compatible with c# (there's actually one but the author only pleted the decompress part). My coding knowedge is limited and I'm not confident I could properly port the code, that's why I decided to use lzs.exe.
Of course I could have attached a batch file and that's it, but ai wanted to make it easier (and probably made it more complicated)

**Comment by nlangh** [comment] 2021-03-15 17:32
No worries, as I already have a workaround for this problem. Maybe I will find the time to work on this issue.

**Comment by suloku** [comment] 2021-03-15 19:19
I recoded it to use qt-lzs (actually I made it so it can be compiled to use either version of lzs).
If it finally works for you I'll upload it.
This version also supports loading and saving decompressed files (auto detects compressed file using the 0xFF08 header).
[ChocoEdit 0.2c-qt.zip](https://github.com/suloku/ChocoEdit/files/6143925/ChocoEdit.0.2c-qt.zip)

**Comment by nlangh** [comment] 2021-03-15 19:30
Thank you very much, this works smoothly.

**Closed as completed** 2021-03-15 22:02 UTC

**Comment by suloku** [comment] 2021-03-15 22:07
Glad this finally is working as I intended 5 years ago
